title: Adrian Kelly
description: PhD student at CmPA, KU Leuven
theme: minima
email: adrian.kelly@kuleuven.be
github_username: akelly810

header_pages:
  - publications.md
  - tests.md

markdown: kramdown
kramdown:
  math_engine: null
